name: Static Binaries

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt update && sudo apt install -y php curl git build-essential cmake libtool musl-dev musl-tools libc6 libc6-dev libc6-dev-i386 libc6-i386 libc6-dev-x32 libstdc++6-i386-cross libstdc++6-amd64-cross libstdc++6-arm64-cross

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
        run: go version

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          version: 2
          command: about

      - name: Clone FrankenPHP
        run: git clone https://github.com/dunglas/frankenphp frankenphp

      - name: Build FrankenPHP
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd frankenphp
          CLEAN=1 PHP_VERSION=8.2 \
          PHP_EXTENSIONS=password-argon2,apcu,bcmath,bz2,ctype,curl,dba,dom,exif,fileinfo,filter,zlib,gd,iconv,igbinary,intl,openssl,mbstring,mbregex,mysqlnd,mysqli,opcache,pcntl,pdo,pdo_mysql,pgsql,pdo_pgsql,sqlite3,pdo_sqlite,phar,posix,readline,session,redis,simplexml,sockets,sysvsem,tokenizer,xml,zip \
          ./build-static.sh
          ls -la dist/*

      - uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: frankenphp/dist/frankenphp-*

  darwin:
    name: Build Mac
    strategy:
      matrix:
        os: [ macos-13, macos-13-arm64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: brew install libiconv bison re2c pkg-config bzip2 liblzf php@8.2 composer go

      - name: Clone FrankenPHP
        run: git clone https://github.com/dunglas/frankenphp frankenphp

      - name: Build FrankenPHP
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd frankenphp
          CLEAN=1 PHP_VERSION=8.2 \
          PHP_EXTENSIONS=password-argon2,apcu,bcmath,bz2,ctype,curl,dba,dom,exif,fileinfo,filter,zlib,gd,iconv,igbinary,intl,openssl,mbstring,mbregex,mysqlnd,mysqli,opcache,pcntl,pdo,pdo_mysql,pgsql,pdo_pgsql,sqlite3,pdo_sqlite,phar,posix,readline,session,redis,simplexml,sockets,sysvsem,tokenizer,xml,zip \
          ./build-static.sh
          ls -la dist/*

      - uses: actions/upload-artifact@v3
        with:
          name: macos-binary
          path: frankenphp/dist/frankenphp-*

#  upload:
#    name: Upload release files
#    runs-on: ubuntu-20.04
#    needs: [
#      webextension,
#      darwin
#    ]
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: webextension
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: extension-safari
#
#      - name: Build Safari
#        run: |
#          ls -la
#
#      - name: Upload release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/v')
#        with:
#          files: |
#            TYPO3-TDK-GitPod-*
